// SimpleChart.idl : ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 产生类型库(SimpleChart.tlb)，该类型库将成为
// SimpleChart.ocx.

#include <olectl.h>
#include <idispids.h>

[ uuid(692E7BD5-A6A8-45D5-98FA-7DAAC3F9DCA1), version(1.0),
  control ]
library SimpleChartLib
{
	importlib(STDOLE_TLB);

	//  CSimpleChartCtrl 的主调度接口
	[ 
		uuid(E6D1E8E1-63E2-4254-BFCB-8C0BE098B3A4)	
	]
	dispinterface _DSimpleChart
	{
		properties:
		methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
			[id(1)] SHORT Init(LONG hWnd, SHORT nWidth, SHORT nHeight, SHORT nLanguage);
			[id(2)] void SetSecurityInf(SHORT nMarketType, SHORT nSecurityType, BSTR bstrCode, BSTR bstrName);
			[id(3)] void AppendData(SHORT nDataType, DOUBLE dData);
			[id(4)] void SetPreDayClosePrice(DOUBLE dData);
			[id(5)] void UpdateLastData(SHORT nDataType, DOUBLE dData);
			[id(6)] void SetViewType(SHORT nViewType);
			[id(7)] void ClearAllData(void);
			[id(8)] void ReDrawChart(void);
			[id(9)] void AddPackData(SHORT nDataType, VARIANT varData);
			[id(10)] void SetXPeriods(DOUBLE dAMBegin,DOUBLE dAMEnd,DOUBLE dPMBegin,DOUBLE dPMEnd);
			[id(11)] void SetHJPeriods(DOUBLE dBegin1, DOUBLE dEnd1, DOUBLE dBegin2, DOUBLE dEnd2, DOUBLE dBegin3, DOUBLE dEnd3, DOUBLE dBegin4, DOUBLE dEnd4);
	};

	//  CSimpleChartCtrl 的事件调度接口

	[ 
		uuid(85FD6665-E52E-416D-A721-53228FD977E0)	
	]
	dispinterface _DSimpleChartEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
	};

	//  CSimpleChartCtrl 的类信息
	[
		uuid(7DED4EF2-EDE3-44DD-8DD0-9BA1FC0CBB8F)
	]
	coclass SimpleChart
	{
		[default] dispinterface _DSimpleChart;
		[default, source] dispinterface _DSimpleChartEvents;
	};

};
