/********************************************************************************
** Form generated from reading UI file 'mainWindow.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QSplitter>
#include <QtWidgets/QWidget>
#include "ClickLabel.h"
#include "markettableview.h"

QT_BEGIN_NAMESPACE

class Ui_mainWindowClass
{
public:
    QWidget *centralWidget;
    QLabel *label_sell_price5;
    QPushButton *pushButton_order;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_sell_price4;
    QLabel *label;
    QLabel *label_sell_vol1;
    QSplitter *splitter;
    MarketTableView *tableViewMarketPrice;
    QPushButton *pushButton_yanqi;
    QLabel *label_32;
    QDoubleSpinBox *spinBox_order_price;
    QLabel *label_sell_vol5;
    QLabel *label_3;
    QLabel *label_sell_price2;
    QComboBox *securityComboBox;
    QLabel *label_4;
    QLabel *label_sell3;
    QLabel *label_sell_price1;
    QLabel *label_buy_price1;
    QLabel *label_sell_vol3;
    QLabel *label_34;
    QPushButton *pushButton_jiaoshou;
    QLabel *label_buy_price5;
    QLabel *label_buy1;
    QPushButton *pushButton_zhonglicang;
    QPushButton *pushButton_preOrder;
    QLabel *label_sell_vol4;
    QLabel *label_buy_price3;
    QLabel *label_buy_vol5;
    QLabel *label_sell5;
    QLabel *label_buy4;
    QPushButton *pushButton_pingcang;
    QLabel *label_sell_vol2;
    QLabel *label_38;
    QLabel *label_buy_vol1;
    QLabel *label_sell_price3;
    QLabel *label_29;
    QLabel *label_sell4;
    QLabel *label_buy_vol2;
    QLabel *label_security_tip;
    QLabel *label_39;
    QLabel *label_36;
    QLabel *label_31;
    QLabel *label_37;
    QLabel *label_sell1;
    QLabel *label_buy_price2;
    QLabel *label_buy5;
    QLabel *label_35;
    QLabel *label_buy_price4;
    QLabel *label_buy_vol3;
    QLabel *label_buy_vol4;
    QLabel *label_33;
    QSpinBox *spinBox_order_num;
    QLabel *label_buy3;
    QLabel *label_2;
    ClickLabel *label_pricetype;
    QPushButton *pushButton_kaicang;
    QLabel *label_buy2;
    QLabel *label_accountname_png;
    QLabel *label_account_change;
    QLabel *label_accountname_val;
    QLabel *label_capital_val;
    QLabel *label_capital_png;
    QLabel *label_capital;
    QLabel *label_gain_png;
    QLabel *label_right;
    QLabel *label_gain_val;
    QLabel *label_right_png;
    QLabel *label_right_val;
    QLabel *label_gain;
    QLabel *label_static_right_png;
    QLabel *label_static_right;
    QLabel *label_static_right_val;
    QLabel *label_high_hand;
    QLabel *label_high_price;
    QLabel *label_date;
    QLabel *label_date_val;
    QLabel *label_sysstatus;
    QLabel *label_sysstatus_val;
    QLabel *label_branch;
    QLabel *label_branch_val;
    QLabel *label_server;
    QLabel *label_server_val;
    QLabel *label_server_status;
    QLabel *label_server_status_val;
    QFrame *line_status;
    QLabel *label_quote_space;
    QLabel *label_quote_space_2;
    QLabel *label_sell_vol6;
    QLabel *label_sell6;
    QLabel *label_sell_price6;
    QLabel *label_30;
    QLabel *label_sell_vol7;
    QLabel *label_sell7;
    QLabel *label_sell_price7;
    QLabel *label_40;
    QLabel *label_sell_vol8;
    QLabel *label_sell8;
    QLabel *label_sell_price8;
    QLabel *label_41;
    QLabel *label_sell_vol9;
    QLabel *label_sell9;
    QLabel *label_sell_price9;
    QLabel *label_42;
    QLabel *label_sell10;
    QLabel *label_sell_vol10;
    QLabel *label_sell_price10;
    QLabel *label_43;
    QLabel *label_buy_price9;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_buy_price10;
    QLabel *label_buy8;
    QLabel *label_buy10;
    QLabel *label_buy7;
    QLabel *label_46;
    QLabel *label_buy_vol10;
    QLabel *label_buy6;
    QLabel *label_buy_price8;
    QLabel *label_buy_vol9;
    QLabel *label_buy_vol6;
    QLabel *label_buy_vol7;
    QLabel *label_buy_price7;
    QLabel *label_buy_price6;
    QLabel *label_47;
    QLabel *label_buy9;
    QLabel *label_buy_vol8;
    QLabel *label_48;
    QLabel *label_sell2;
    QLabel *label_low_price;
    QLabel *label_9;
    QLabel *label_6;
    QPushButton *pushButton_sell;
    QPushButton *pushButton_buy;
    QPushButton *pushButton_closePosi;
    QPushButton *pushButton_reverse_order;
    QPushButton *pushButton_changeorder;
    QPushButton *pushButton_cancelorder;
    QPushButton *pushButton_cancelallorder;
    QPushButton *pushButton_pre_send;
    QPushButton *pushButton_clear_send;
    QPushButton *pushButton_pre_delete;
    QPushButton *pushButton_getgoods;
    QPushButton *pushButton_FunfInOut;
    QComboBox *comboBox_account;
    QLabel *label_account_name;
    QPushButton *pushButton_add;
    QLabel *label_account_risk;
    QLabel *label_account_risk_val;
    QComboBox *indiComboBox;
    QMenuBar *menuBar;

    void setupUi(QMainWindow *mainWindowClass)
    {
        if (mainWindowClass->objectName().isEmpty())
            mainWindowClass->setObjectName(QStringLiteral("mainWindowClass"));
        mainWindowClass->resize(1805, 1080);
        mainWindowClass->setMinimumSize(QSize(1320, 880));
        centralWidget = new QWidget(mainWindowClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        centralWidget->setMinimumSize(QSize(700, 600));
        label_sell_price5 = new QLabel(centralWidget);
        label_sell_price5->setObjectName(QStringLiteral("label_sell_price5"));
        label_sell_price5->setGeometry(QRect(480, 160, 24, 12));
        pushButton_order = new QPushButton(centralWidget);
        pushButton_order->setObjectName(QStringLiteral("pushButton_order"));
        pushButton_order->setGeometry(QRect(30, 300, 75, 23));
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(250, 240, 21, 16));
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(250, 260, 21, 16));
        label_sell_price4 = new QLabel(centralWidget);
        label_sell_price4->setObjectName(QStringLiteral("label_sell_price4"));
        label_sell_price4->setGeometry(QRect(480, 180, 24, 12));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(40, 90, 54, 12));
        label_sell_vol1 = new QLabel(centralWidget);
        label_sell_vol1->setObjectName(QStringLiteral("label_sell_vol1"));
        label_sell_vol1->setGeometry(QRect(550, 240, 12, 12));
        splitter = new QSplitter(centralWidget);
        splitter->setObjectName(QStringLiteral("splitter"));
        splitter->setGeometry(QRect(680, 60, 461, 201));
        splitter->setOrientation(Qt::Horizontal);
        tableViewMarketPrice = new MarketTableView(splitter);
        tableViewMarketPrice->setObjectName(QStringLiteral("tableViewMarketPrice"));
        splitter->addWidget(tableViewMarketPrice);
        pushButton_yanqi = new QPushButton(centralWidget);
        pushButton_yanqi->setObjectName(QStringLiteral("pushButton_yanqi"));
        pushButton_yanqi->setGeometry(QRect(100, 130, 75, 23));
        pushButton_yanqi->setCheckable(true);
        label_32 = new QLabel(centralWidget);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(520, 200, 6, 12));
        spinBox_order_price = new QDoubleSpinBox(centralWidget);
        spinBox_order_price->setObjectName(QStringLiteral("spinBox_order_price"));
        spinBox_order_price->setGeometry(QRect(100, 260, 131, 22));
        spinBox_order_price->setStyleSheet(QStringLiteral(""));
        label_sell_vol5 = new QLabel(centralWidget);
        label_sell_vol5->setObjectName(QStringLiteral("label_sell_vol5"));
        label_sell_vol5->setGeometry(QRect(550, 160, 12, 12));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(40, 200, 54, 12));
        label_sell_price2 = new QLabel(centralWidget);
        label_sell_price2->setObjectName(QStringLiteral("label_sell_price2"));
        label_sell_price2->setGeometry(QRect(480, 220, 24, 12));
        securityComboBox = new QComboBox(centralWidget);
        securityComboBox->setObjectName(QStringLiteral("securityComboBox"));
        securityComboBox->setGeometry(QRect(100, 90, 101, 22));
        securityComboBox->setMinimumSize(QSize(100, 0));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(40, 230, 54, 12));
        label_sell3 = new QLabel(centralWidget);
        label_sell3->setObjectName(QStringLiteral("label_sell3"));
        label_sell3->setGeometry(QRect(420, 200, 31, 16));
        label_sell_price1 = new QLabel(centralWidget);
        label_sell_price1->setObjectName(QStringLiteral("label_sell_price1"));
        label_sell_price1->setGeometry(QRect(480, 240, 24, 12));
        label_buy_price1 = new QLabel(centralWidget);
        label_buy_price1->setObjectName(QStringLiteral("label_buy_price1"));
        label_buy_price1->setGeometry(QRect(480, 290, 24, 12));
        label_sell_vol3 = new QLabel(centralWidget);
        label_sell_vol3->setObjectName(QStringLiteral("label_sell_vol3"));
        label_sell_vol3->setGeometry(QRect(550, 200, 12, 12));
        label_34 = new QLabel(centralWidget);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(520, 240, 6, 12));
        pushButton_jiaoshou = new QPushButton(centralWidget);
        pushButton_jiaoshou->setObjectName(QStringLiteral("pushButton_jiaoshou"));
        pushButton_jiaoshou->setGeometry(QRect(200, 130, 75, 23));
        pushButton_jiaoshou->setCheckable(true);
        label_buy_price5 = new QLabel(centralWidget);
        label_buy_price5->setObjectName(QStringLiteral("label_buy_price5"));
        label_buy_price5->setGeometry(QRect(480, 370, 24, 12));
        label_buy1 = new QLabel(centralWidget);
        label_buy1->setObjectName(QStringLiteral("label_buy1"));
        label_buy1->setGeometry(QRect(420, 290, 31, 16));
        pushButton_zhonglicang = new QPushButton(centralWidget);
        pushButton_zhonglicang->setObjectName(QStringLiteral("pushButton_zhonglicang"));
        pushButton_zhonglicang->setGeometry(QRect(290, 130, 75, 23));
        pushButton_zhonglicang->setCheckable(true);
        pushButton_preOrder = new QPushButton(centralWidget);
        pushButton_preOrder->setObjectName(QStringLiteral("pushButton_preOrder"));
        pushButton_preOrder->setGeometry(QRect(130, 300, 75, 23));
        label_sell_vol4 = new QLabel(centralWidget);
        label_sell_vol4->setObjectName(QStringLiteral("label_sell_vol4"));
        label_sell_vol4->setGeometry(QRect(550, 180, 12, 12));
        label_buy_price3 = new QLabel(centralWidget);
        label_buy_price3->setObjectName(QStringLiteral("label_buy_price3"));
        label_buy_price3->setGeometry(QRect(480, 330, 24, 12));
        label_buy_vol5 = new QLabel(centralWidget);
        label_buy_vol5->setObjectName(QStringLiteral("label_buy_vol5"));
        label_buy_vol5->setGeometry(QRect(550, 370, 12, 12));
        label_sell5 = new QLabel(centralWidget);
        label_sell5->setObjectName(QStringLiteral("label_sell5"));
        label_sell5->setGeometry(QRect(420, 160, 31, 16));
        label_buy4 = new QLabel(centralWidget);
        label_buy4->setObjectName(QStringLiteral("label_buy4"));
        label_buy4->setGeometry(QRect(420, 350, 31, 16));
        pushButton_pingcang = new QPushButton(centralWidget);
        pushButton_pingcang->setObjectName(QStringLiteral("pushButton_pingcang"));
        pushButton_pingcang->setGeometry(QRect(200, 200, 75, 23));
        pushButton_pingcang->setCheckable(true);
        label_sell_vol2 = new QLabel(centralWidget);
        label_sell_vol2->setObjectName(QStringLiteral("label_sell_vol2"));
        label_sell_vol2->setGeometry(QRect(550, 220, 12, 12));
        label_38 = new QLabel(centralWidget);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(520, 350, 6, 12));
        label_buy_vol1 = new QLabel(centralWidget);
        label_buy_vol1->setObjectName(QStringLiteral("label_buy_vol1"));
        label_buy_vol1->setGeometry(QRect(550, 290, 12, 12));
        label_sell_price3 = new QLabel(centralWidget);
        label_sell_price3->setObjectName(QStringLiteral("label_sell_price3"));
        label_sell_price3->setGeometry(QRect(480, 200, 24, 12));
        label_29 = new QLabel(centralWidget);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(520, 160, 6, 12));
        label_sell4 = new QLabel(centralWidget);
        label_sell4->setObjectName(QStringLiteral("label_sell4"));
        label_sell4->setGeometry(QRect(420, 180, 31, 16));
        label_buy_vol2 = new QLabel(centralWidget);
        label_buy_vol2->setObjectName(QStringLiteral("label_buy_vol2"));
        label_buy_vol2->setGeometry(QRect(550, 310, 12, 12));
        label_security_tip = new QLabel(centralWidget);
        label_security_tip->setObjectName(QStringLiteral("label_security_tip"));
        label_security_tip->setGeometry(QRect(220, 90, 54, 12));
        label_39 = new QLabel(centralWidget);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(520, 370, 6, 12));
        label_36 = new QLabel(centralWidget);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(520, 310, 6, 12));
        label_31 = new QLabel(centralWidget);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(520, 180, 6, 12));
        label_37 = new QLabel(centralWidget);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(520, 330, 6, 12));
        label_sell1 = new QLabel(centralWidget);
        label_sell1->setObjectName(QStringLiteral("label_sell1"));
        label_sell1->setGeometry(QRect(420, 240, 31, 16));
        label_buy_price2 = new QLabel(centralWidget);
        label_buy_price2->setObjectName(QStringLiteral("label_buy_price2"));
        label_buy_price2->setGeometry(QRect(480, 310, 24, 12));
        label_buy5 = new QLabel(centralWidget);
        label_buy5->setObjectName(QStringLiteral("label_buy5"));
        label_buy5->setGeometry(QRect(420, 370, 31, 16));
        label_35 = new QLabel(centralWidget);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(520, 290, 6, 12));
        label_buy_price4 = new QLabel(centralWidget);
        label_buy_price4->setObjectName(QStringLiteral("label_buy_price4"));
        label_buy_price4->setGeometry(QRect(480, 350, 24, 12));
        label_buy_vol3 = new QLabel(centralWidget);
        label_buy_vol3->setObjectName(QStringLiteral("label_buy_vol3"));
        label_buy_vol3->setGeometry(QRect(550, 330, 12, 12));
        label_buy_vol4 = new QLabel(centralWidget);
        label_buy_vol4->setObjectName(QStringLiteral("label_buy_vol4"));
        label_buy_vol4->setGeometry(QRect(550, 350, 12, 12));
        label_33 = new QLabel(centralWidget);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(520, 220, 6, 12));
        spinBox_order_num = new QSpinBox(centralWidget);
        spinBox_order_num->setObjectName(QStringLiteral("spinBox_order_num"));
        spinBox_order_num->setGeometry(QRect(100, 230, 131, 22));
        spinBox_order_num->setStyleSheet(QStringLiteral(""));
        spinBox_order_num->setMaximum(1000000);
        label_buy3 = new QLabel(centralWidget);
        label_buy3->setObjectName(QStringLiteral("label_buy3"));
        label_buy3->setGeometry(QRect(420, 330, 31, 16));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(40, 130, 54, 12));
        label_pricetype = new ClickLabel(centralWidget);
        label_pricetype->setObjectName(QStringLiteral("label_pricetype"));
        label_pricetype->setGeometry(QRect(30, 260, 54, 12));
        pushButton_kaicang = new QPushButton(centralWidget);
        pushButton_kaicang->setObjectName(QStringLiteral("pushButton_kaicang"));
        pushButton_kaicang->setGeometry(QRect(100, 200, 75, 23));
        pushButton_kaicang->setCheckable(true);
        label_buy2 = new QLabel(centralWidget);
        label_buy2->setObjectName(QStringLiteral("label_buy2"));
        label_buy2->setGeometry(QRect(420, 310, 31, 16));
        label_accountname_png = new QLabel(centralWidget);
        label_accountname_png->setObjectName(QStringLiteral("label_accountname_png"));
        label_accountname_png->setGeometry(QRect(250, 10, 54, 12));
        label_account_change = new QLabel(centralWidget);
        label_account_change->setObjectName(QStringLiteral("label_account_change"));
        label_account_change->setGeometry(QRect(10, 0, 71, 31));
        label_accountname_val = new QLabel(centralWidget);
        label_accountname_val->setObjectName(QStringLiteral("label_accountname_val"));
        label_accountname_val->setGeometry(QRect(340, 10, 54, 12));
        label_capital_val = new QLabel(centralWidget);
        label_capital_val->setObjectName(QStringLiteral("label_capital_val"));
        label_capital_val->setGeometry(QRect(550, 10, 101, 16));
        label_capital_png = new QLabel(centralWidget);
        label_capital_png->setObjectName(QStringLiteral("label_capital_png"));
        label_capital_png->setGeometry(QRect(430, 10, 54, 12));
        label_capital = new QLabel(centralWidget);
        label_capital->setObjectName(QStringLiteral("label_capital"));
        label_capital->setGeometry(QRect(480, 10, 71, 20));
        label_gain_png = new QLabel(centralWidget);
        label_gain_png->setObjectName(QStringLiteral("label_gain_png"));
        label_gain_png->setGeometry(QRect(660, 10, 54, 12));
        label_right = new QLabel(centralWidget);
        label_right->setObjectName(QStringLiteral("label_right"));
        label_right->setGeometry(QRect(950, 10, 71, 20));
        label_gain_val = new QLabel(centralWidget);
        label_gain_val->setObjectName(QStringLiteral("label_gain_val"));
        label_gain_val->setGeometry(QRect(780, 10, 101, 16));
        label_right_png = new QLabel(centralWidget);
        label_right_png->setObjectName(QStringLiteral("label_right_png"));
        label_right_png->setGeometry(QRect(890, 10, 54, 12));
        label_right_val = new QLabel(centralWidget);
        label_right_val->setObjectName(QStringLiteral("label_right_val"));
        label_right_val->setGeometry(QRect(1030, 10, 101, 16));
        label_gain = new QLabel(centralWidget);
        label_gain->setObjectName(QStringLiteral("label_gain"));
        label_gain->setGeometry(QRect(700, 10, 71, 20));
        label_static_right_png = new QLabel(centralWidget);
        label_static_right_png->setObjectName(QStringLiteral("label_static_right_png"));
        label_static_right_png->setGeometry(QRect(1160, 10, 54, 12));
        label_static_right = new QLabel(centralWidget);
        label_static_right->setObjectName(QStringLiteral("label_static_right"));
        label_static_right->setGeometry(QRect(1213, 10, 81, 20));
        label_static_right_val = new QLabel(centralWidget);
        label_static_right_val->setObjectName(QStringLiteral("label_static_right_val"));
        label_static_right_val->setGeometry(QRect(1300, 10, 111, 16));
        label_high_hand = new QLabel(centralWidget);
        label_high_hand->setObjectName(QStringLiteral("label_high_hand"));
        label_high_hand->setGeometry(QRect(283, 240, 111, 20));
        label_high_price = new QLabel(centralWidget);
        label_high_price->setObjectName(QStringLiteral("label_high_price"));
        label_high_price->setGeometry(QRect(283, 260, 81, 20));
        label_date = new QLabel(centralWidget);
        label_date->setObjectName(QStringLiteral("label_date"));
        label_date->setGeometry(QRect(80, 690, 54, 12));
        label_date_val = new QLabel(centralWidget);
        label_date_val->setObjectName(QStringLiteral("label_date_val"));
        label_date_val->setGeometry(QRect(143, 690, 71, 20));
        label_sysstatus = new QLabel(centralWidget);
        label_sysstatus->setObjectName(QStringLiteral("label_sysstatus"));
        label_sysstatus->setGeometry(QRect(260, 690, 54, 12));
        label_sysstatus_val = new QLabel(centralWidget);
        label_sysstatus_val->setObjectName(QStringLiteral("label_sysstatus_val"));
        label_sysstatus_val->setGeometry(QRect(340, 690, 71, 16));
        label_branch = new QLabel(centralWidget);
        label_branch->setObjectName(QStringLiteral("label_branch"));
        label_branch->setGeometry(QRect(463, 690, 101, 20));
        label_branch_val = new QLabel(centralWidget);
        label_branch_val->setObjectName(QStringLiteral("label_branch_val"));
        label_branch_val->setGeometry(QRect(590, 690, 201, 16));
        label_server = new QLabel(centralWidget);
        label_server->setObjectName(QStringLiteral("label_server"));
        label_server->setGeometry(QRect(830, 690, 54, 12));
        label_server_val = new QLabel(centralWidget);
        label_server_val->setObjectName(QStringLiteral("label_server_val"));
        label_server_val->setGeometry(QRect(900, 690, 121, 20));
        label_server_status = new QLabel(centralWidget);
        label_server_status->setObjectName(QStringLiteral("label_server_status"));
        label_server_status->setGeometry(QRect(1030, 690, 91, 16));
        label_server_status_val = new QLabel(centralWidget);
        label_server_status_val->setObjectName(QStringLiteral("label_server_status_val"));
        label_server_status_val->setGeometry(QRect(1130, 690, 54, 12));
        line_status = new QFrame(centralWidget);
        line_status->setObjectName(QStringLiteral("line_status"));
        line_status->setGeometry(QRect(70, 660, 1331, 16));
        line_status->setFrameShape(QFrame::HLine);
        line_status->setFrameShadow(QFrame::Sunken);
        label_quote_space = new QLabel(centralWidget);
        label_quote_space->setObjectName(QStringLiteral("label_quote_space"));
        label_quote_space->setGeometry(QRect(420, 260, 81, 16));
        label_quote_space->setLayoutDirection(Qt::RightToLeft);
        label_quote_space_2 = new QLabel(centralWidget);
        label_quote_space_2->setObjectName(QStringLiteral("label_quote_space_2"));
        label_quote_space_2->setGeometry(QRect(500, 260, 81, 16));
        label_sell_vol6 = new QLabel(centralWidget);
        label_sell_vol6->setObjectName(QStringLiteral("label_sell_vol6"));
        label_sell_vol6->setGeometry(QRect(550, 140, 12, 12));
        label_sell6 = new QLabel(centralWidget);
        label_sell6->setObjectName(QStringLiteral("label_sell6"));
        label_sell6->setGeometry(QRect(420, 140, 31, 16));
        label_sell_price6 = new QLabel(centralWidget);
        label_sell_price6->setObjectName(QStringLiteral("label_sell_price6"));
        label_sell_price6->setGeometry(QRect(480, 140, 24, 12));
        label_30 = new QLabel(centralWidget);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(520, 140, 6, 12));
        label_sell_vol7 = new QLabel(centralWidget);
        label_sell_vol7->setObjectName(QStringLiteral("label_sell_vol7"));
        label_sell_vol7->setGeometry(QRect(550, 120, 12, 12));
        label_sell7 = new QLabel(centralWidget);
        label_sell7->setObjectName(QStringLiteral("label_sell7"));
        label_sell7->setGeometry(QRect(420, 120, 31, 16));
        label_sell_price7 = new QLabel(centralWidget);
        label_sell_price7->setObjectName(QStringLiteral("label_sell_price7"));
        label_sell_price7->setGeometry(QRect(480, 120, 24, 12));
        label_40 = new QLabel(centralWidget);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(520, 120, 6, 12));
        label_sell_vol8 = new QLabel(centralWidget);
        label_sell_vol8->setObjectName(QStringLiteral("label_sell_vol8"));
        label_sell_vol8->setGeometry(QRect(550, 100, 12, 12));
        label_sell8 = new QLabel(centralWidget);
        label_sell8->setObjectName(QStringLiteral("label_sell8"));
        label_sell8->setGeometry(QRect(420, 100, 31, 16));
        label_sell_price8 = new QLabel(centralWidget);
        label_sell_price8->setObjectName(QStringLiteral("label_sell_price8"));
        label_sell_price8->setGeometry(QRect(480, 100, 24, 12));
        label_41 = new QLabel(centralWidget);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(520, 100, 6, 12));
        label_sell_vol9 = new QLabel(centralWidget);
        label_sell_vol9->setObjectName(QStringLiteral("label_sell_vol9"));
        label_sell_vol9->setGeometry(QRect(550, 80, 12, 12));
        label_sell9 = new QLabel(centralWidget);
        label_sell9->setObjectName(QStringLiteral("label_sell9"));
        label_sell9->setGeometry(QRect(420, 80, 31, 16));
        label_sell_price9 = new QLabel(centralWidget);
        label_sell_price9->setObjectName(QStringLiteral("label_sell_price9"));
        label_sell_price9->setGeometry(QRect(480, 80, 24, 12));
        label_42 = new QLabel(centralWidget);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(520, 80, 6, 12));
        label_sell10 = new QLabel(centralWidget);
        label_sell10->setObjectName(QStringLiteral("label_sell10"));
        label_sell10->setGeometry(QRect(420, 60, 31, 16));
        label_sell_vol10 = new QLabel(centralWidget);
        label_sell_vol10->setObjectName(QStringLiteral("label_sell_vol10"));
        label_sell_vol10->setGeometry(QRect(550, 60, 12, 12));
        label_sell_price10 = new QLabel(centralWidget);
        label_sell_price10->setObjectName(QStringLiteral("label_sell_price10"));
        label_sell_price10->setGeometry(QRect(480, 60, 24, 12));
        label_43 = new QLabel(centralWidget);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(520, 60, 6, 12));
        label_buy_price9 = new QLabel(centralWidget);
        label_buy_price9->setObjectName(QStringLiteral("label_buy_price9"));
        label_buy_price9->setGeometry(QRect(480, 450, 24, 12));
        label_44 = new QLabel(centralWidget);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(520, 470, 6, 12));
        label_45 = new QLabel(centralWidget);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(520, 430, 6, 12));
        label_buy_price10 = new QLabel(centralWidget);
        label_buy_price10->setObjectName(QStringLiteral("label_buy_price10"));
        label_buy_price10->setGeometry(QRect(480, 470, 24, 12));
        label_buy8 = new QLabel(centralWidget);
        label_buy8->setObjectName(QStringLiteral("label_buy8"));
        label_buy8->setGeometry(QRect(420, 430, 31, 16));
        label_buy10 = new QLabel(centralWidget);
        label_buy10->setObjectName(QStringLiteral("label_buy10"));
        label_buy10->setGeometry(QRect(420, 470, 31, 16));
        label_buy7 = new QLabel(centralWidget);
        label_buy7->setObjectName(QStringLiteral("label_buy7"));
        label_buy7->setGeometry(QRect(420, 410, 31, 16));
        label_46 = new QLabel(centralWidget);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(520, 410, 6, 12));
        label_buy_vol10 = new QLabel(centralWidget);
        label_buy_vol10->setObjectName(QStringLiteral("label_buy_vol10"));
        label_buy_vol10->setGeometry(QRect(550, 470, 12, 12));
        label_buy6 = new QLabel(centralWidget);
        label_buy6->setObjectName(QStringLiteral("label_buy6"));
        label_buy6->setGeometry(QRect(420, 390, 31, 16));
        label_buy_price8 = new QLabel(centralWidget);
        label_buy_price8->setObjectName(QStringLiteral("label_buy_price8"));
        label_buy_price8->setGeometry(QRect(480, 430, 24, 12));
        label_buy_vol9 = new QLabel(centralWidget);
        label_buy_vol9->setObjectName(QStringLiteral("label_buy_vol9"));
        label_buy_vol9->setGeometry(QRect(550, 450, 12, 12));
        label_buy_vol6 = new QLabel(centralWidget);
        label_buy_vol6->setObjectName(QStringLiteral("label_buy_vol6"));
        label_buy_vol6->setGeometry(QRect(550, 390, 12, 12));
        label_buy_vol7 = new QLabel(centralWidget);
        label_buy_vol7->setObjectName(QStringLiteral("label_buy_vol7"));
        label_buy_vol7->setGeometry(QRect(550, 410, 12, 12));
        label_buy_price7 = new QLabel(centralWidget);
        label_buy_price7->setObjectName(QStringLiteral("label_buy_price7"));
        label_buy_price7->setGeometry(QRect(480, 410, 24, 12));
        label_buy_price6 = new QLabel(centralWidget);
        label_buy_price6->setObjectName(QStringLiteral("label_buy_price6"));
        label_buy_price6->setGeometry(QRect(480, 390, 24, 12));
        label_47 = new QLabel(centralWidget);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(520, 390, 6, 12));
        label_buy9 = new QLabel(centralWidget);
        label_buy9->setObjectName(QStringLiteral("label_buy9"));
        label_buy9->setGeometry(QRect(420, 450, 31, 16));
        label_buy_vol8 = new QLabel(centralWidget);
        label_buy_vol8->setObjectName(QStringLiteral("label_buy_vol8"));
        label_buy_vol8->setGeometry(QRect(550, 430, 12, 12));
        label_48 = new QLabel(centralWidget);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(520, 450, 6, 12));
        label_sell2 = new QLabel(centralWidget);
        label_sell2->setObjectName(QStringLiteral("label_sell2"));
        label_sell2->setGeometry(QRect(420, 220, 41, 16));
        label_low_price = new QLabel(centralWidget);
        label_low_price->setObjectName(QStringLiteral("label_low_price"));
        label_low_price->setGeometry(QRect(283, 280, 81, 20));
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(250, 280, 21, 16));
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(40, 170, 54, 12));
        pushButton_sell = new QPushButton(centralWidget);
        pushButton_sell->setObjectName(QStringLiteral("pushButton_sell"));
        pushButton_sell->setGeometry(QRect(200, 170, 75, 23));
        pushButton_sell->setCheckable(true);
        pushButton_buy = new QPushButton(centralWidget);
        pushButton_buy->setObjectName(QStringLiteral("pushButton_buy"));
        pushButton_buy->setGeometry(QRect(100, 170, 75, 23));
        pushButton_buy->setCheckable(true);
        pushButton_closePosi = new QPushButton(centralWidget);
        pushButton_closePosi->setObjectName(QStringLiteral("pushButton_closePosi"));
        pushButton_closePosi->setGeometry(QRect(340, 600, 75, 23));
        pushButton_reverse_order = new QPushButton(centralWidget);
        pushButton_reverse_order->setObjectName(QStringLiteral("pushButton_reverse_order"));
        pushButton_reverse_order->setGeometry(QRect(340, 630, 75, 23));
        pushButton_changeorder = new QPushButton(centralWidget);
        pushButton_changeorder->setObjectName(QStringLiteral("pushButton_changeorder"));
        pushButton_changeorder->setGeometry(QRect(450, 630, 75, 23));
        pushButton_cancelorder = new QPushButton(centralWidget);
        pushButton_cancelorder->setObjectName(QStringLiteral("pushButton_cancelorder"));
        pushButton_cancelorder->setGeometry(QRect(450, 570, 75, 23));
        pushButton_cancelallorder = new QPushButton(centralWidget);
        pushButton_cancelallorder->setObjectName(QStringLiteral("pushButton_cancelallorder"));
        pushButton_cancelallorder->setGeometry(QRect(450, 600, 75, 23));
        pushButton_pre_send = new QPushButton(centralWidget);
        pushButton_pre_send->setObjectName(QStringLiteral("pushButton_pre_send"));
        pushButton_pre_send->setGeometry(QRect(600, 590, 81, 23));
        pushButton_clear_send = new QPushButton(centralWidget);
        pushButton_clear_send->setObjectName(QStringLiteral("pushButton_clear_send"));
        pushButton_clear_send->setGeometry(QRect(600, 620, 81, 23));
        pushButton_pre_delete = new QPushButton(centralWidget);
        pushButton_pre_delete->setObjectName(QStringLiteral("pushButton_pre_delete"));
        pushButton_pre_delete->setGeometry(QRect(600, 560, 81, 23));
        pushButton_getgoods = new QPushButton(centralWidget);
        pushButton_getgoods->setObjectName(QStringLiteral("pushButton_getgoods"));
        pushButton_getgoods->setGeometry(QRect(160, 630, 75, 23));
        pushButton_FunfInOut = new QPushButton(centralWidget);
        pushButton_FunfInOut->setObjectName(QStringLiteral("pushButton_FunfInOut"));
        pushButton_FunfInOut->setGeometry(QRect(250, 630, 75, 23));
        comboBox_account = new QComboBox(centralWidget);
        comboBox_account->setObjectName(QStringLiteral("comboBox_account"));
        comboBox_account->setGeometry(QRect(80, 0, 121, 22));
        comboBox_account->setMinimumSize(QSize(120, 0));
        label_account_name = new QLabel(centralWidget);
        label_account_name->setObjectName(QStringLiteral("label_account_name"));
        label_account_name->setGeometry(QRect(270, 0, 71, 31));
        pushButton_add = new QPushButton(centralWidget);
        pushButton_add->setObjectName(QStringLiteral("pushButton_add"));
        pushButton_add->setGeometry(QRect(200, 0, 60, 23));
        pushButton_add->setStyleSheet(QStringLiteral(""));
        label_account_risk = new QLabel(centralWidget);
        label_account_risk->setObjectName(QStringLiteral("label_account_risk"));
        label_account_risk->setGeometry(QRect(1420, 10, 61, 20));
        label_account_risk->setStyleSheet(QStringLiteral(""));
        label_account_risk_val = new QLabel(centralWidget);
        label_account_risk_val->setObjectName(QStringLiteral("label_account_risk_val"));
        label_account_risk_val->setGeometry(QRect(1500, 10, 61, 20));
        indiComboBox = new QComboBox(centralWidget);
        indiComboBox->setObjectName(QStringLiteral("indiComboBox"));
        indiComboBox->setGeometry(QRect(220, 300, 91, 22));
        mainWindowClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(mainWindowClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1805, 23));
        mainWindowClass->setMenuBar(menuBar);

        retranslateUi(mainWindowClass);
        QObject::connect(pushButton_order, SIGNAL(clicked()), mainWindowClass, SLOT(slotSendOrder()));
        QObject::connect(pushButton_jiaoshou, SIGNAL(clicked()), mainWindowClass, SLOT(slotChangeOrderType2()));
        QObject::connect(pushButton_zhonglicang, SIGNAL(clicked()), mainWindowClass, SLOT(slotChangeOrderType3()));
        QObject::connect(pushButton_kaicang, SIGNAL(clicked()), mainWindowClass, SLOT(slotChangeOpenCloseType()));
        QObject::connect(pushButton_pingcang, SIGNAL(clicked()), mainWindowClass, SLOT(slotChangeOpenCloseType2()));
        QObject::connect(pushButton_yanqi, SIGNAL(clicked()), mainWindowClass, SLOT(slotChangeOrderType()));
        QObject::connect(pushButton_buy, SIGNAL(clicked()), mainWindowClass, SLOT(slotChangeBuyType()));
        QObject::connect(pushButton_sell, SIGNAL(clicked()), mainWindowClass, SLOT(slotChangeSellType()));
        QObject::connect(pushButton_preOrder, SIGNAL(clicked()), mainWindowClass, SLOT(slotPreOrder()));

        QMetaObject::connectSlotsByName(mainWindowClass);
    } // setupUi

    void retranslateUi(QMainWindow *mainWindowClass)
    {
        mainWindowClass->setWindowTitle(QApplication::translate("mainWindowClass", "mainWindow", Q_NULLPTR));
        label_sell_price5->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        pushButton_order->setText(QApplication::translate("mainWindowClass", "\344\270\213\345\215\225", Q_NULLPTR));
        label_7->setText(QApplication::translate("mainWindowClass", "<=", Q_NULLPTR));
        label_8->setText(QApplication::translate("mainWindowClass", "<=", Q_NULLPTR));
        label_sell_price4->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label->setText(QApplication::translate("mainWindowClass", "\345\220\210\347\272\246", Q_NULLPTR));
        label_sell_vol1->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        pushButton_yanqi->setText(QApplication::translate("mainWindowClass", "\345\273\266\346\234\237", Q_NULLPTR));
        label_32->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_sell_vol5->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_3->setText(QApplication::translate("mainWindowClass", "\345\274\200\345\271\263", Q_NULLPTR));
        label_sell_price2->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_4->setText(QApplication::translate("mainWindowClass", "\346\211\213\346\225\260", Q_NULLPTR));
        label_sell3->setText(QApplication::translate("mainWindowClass", "\345\215\226\344\270\211", Q_NULLPTR));
        label_sell_price1->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_buy_price1->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_sell_vol3->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_34->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        pushButton_jiaoshou->setText(QApplication::translate("mainWindowClass", "\344\272\244\346\224\266", Q_NULLPTR));
        label_buy_price5->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_buy1->setText(QApplication::translate("mainWindowClass", "\344\271\260\344\270\200", Q_NULLPTR));
        pushButton_zhonglicang->setText(QApplication::translate("mainWindowClass", "\344\270\255\347\253\213\344\273\223", Q_NULLPTR));
        pushButton_preOrder->setText(QApplication::translate("mainWindowClass", "\351\242\204\345\237\213\345\215\225", Q_NULLPTR));
        label_sell_vol4->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_buy_price3->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_buy_vol5->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_sell5->setText(QApplication::translate("mainWindowClass", "\345\215\226\344\272\224", Q_NULLPTR));
        label_buy4->setText(QApplication::translate("mainWindowClass", "\344\271\260\345\233\233", Q_NULLPTR));
        pushButton_pingcang->setText(QApplication::translate("mainWindowClass", "\345\271\263\344\273\223", Q_NULLPTR));
        label_sell_vol2->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_38->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_buy_vol1->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_sell_price3->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_29->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_sell4->setText(QApplication::translate("mainWindowClass", "\345\215\226\345\233\233", Q_NULLPTR));
        label_buy_vol2->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_security_tip->setText(QApplication::translate("mainWindowClass", "0.00\345\215\203\345\205\213", Q_NULLPTR));
        label_39->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_36->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_31->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_37->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_sell1->setText(QApplication::translate("mainWindowClass", "\345\215\226\344\270\200", Q_NULLPTR));
        label_buy_price2->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_buy5->setText(QApplication::translate("mainWindowClass", "\344\271\260\344\272\224", Q_NULLPTR));
        label_35->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_buy_price4->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_buy_vol3->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_buy_vol4->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_33->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_buy3->setText(QApplication::translate("mainWindowClass", "\344\271\260\344\270\211", Q_NULLPTR));
        label_2->setText(QApplication::translate("mainWindowClass", "\346\226\271\345\274\217", Q_NULLPTR));
        label_pricetype->setText(QApplication::translate("mainWindowClass", "\346\214\207\345\256\232\344\273\267", Q_NULLPTR));
        pushButton_kaicang->setText(QApplication::translate("mainWindowClass", "\345\274\200\344\273\223", Q_NULLPTR));
        label_buy2->setText(QApplication::translate("mainWindowClass", "\344\271\260\344\272\214", Q_NULLPTR));
        label_accountname_png->setText(QApplication::translate("mainWindowClass", "\345\233\276\347\211\207", Q_NULLPTR));
        label_account_change->setText(QApplication::translate("mainWindowClass", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">\345\210\207\346\215\242\350\264\246\346\210\267:</span></p></body></html>", Q_NULLPTR));
        label_accountname_val->setText(QApplication::translate("mainWindowClass", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">\347\216\213\345\260\217\347\231\275</span></p></body></html>", Q_NULLPTR));
        label_capital_val->setText(QApplication::translate("mainWindowClass", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">218\357\274\214154.48</span></p></body></html>", Q_NULLPTR));
        label_capital_png->setText(QApplication::translate("mainWindowClass", "\345\233\276\347\211\207", Q_NULLPTR));
        label_capital->setText(QApplication::translate("mainWindowClass", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">\345\217\257\347\224\250\350\265\204\351\207\221:</span></p></body></html>", Q_NULLPTR));
        label_gain_png->setText(QApplication::translate("mainWindowClass", "\345\233\276\347\211\207", Q_NULLPTR));
        label_right->setText(QApplication::translate("mainWindowClass", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">\345\212\250\346\200\201\346\235\203\347\233\212:</span></p></body></html>", Q_NULLPTR));
        label_gain_val->setText(QApplication::translate("mainWindowClass", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">408.05</span></p></body></html>", Q_NULLPTR));
        label_right_png->setText(QApplication::translate("mainWindowClass", "\345\233\276\347\211\207", Q_NULLPTR));
        label_right_val->setText(QApplication::translate("mainWindowClass", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">287\357\274\214394.12</span></p></body></html>", Q_NULLPTR));
        label_gain->setText(QApplication::translate("mainWindowClass", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">\346\265\256\345\212\250\347\233\210\344\272\217:</span></p></body></html>", Q_NULLPTR));
        label_static_right_png->setText(QApplication::translate("mainWindowClass", "\345\233\276\347\211\207", Q_NULLPTR));
        label_static_right->setText(QApplication::translate("mainWindowClass", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">\351\235\231\346\200\201\346\235\203\347\233\212:</span></p></body></html>", Q_NULLPTR));
        label_static_right_val->setText(QApplication::translate("mainWindowClass", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">286\357\274\214982.12</span></p></body></html>", Q_NULLPTR));
        label_high_hand->setText(QApplication::translate("mainWindowClass", "00.00", Q_NULLPTR));
        label_high_price->setText(QApplication::translate("mainWindowClass", "00.00", Q_NULLPTR));
        label_date->setText(QApplication::translate("mainWindowClass", "\344\272\244\346\230\223\346\227\245\346\234\237:", Q_NULLPTR));
        label_date_val->setText(QApplication::translate("mainWindowClass", "2017/01/01", Q_NULLPTR));
        label_sysstatus->setText(QApplication::translate("mainWindowClass", "\347\263\273\347\273\237\347\212\266\346\200\201:", Q_NULLPTR));
        label_sysstatus_val->setText(QApplication::translate("mainWindowClass", "\345\210\235\345\247\213\345\214\226\345\256\214\346\210\220", Q_NULLPTR));
        label_branch->setText(QApplication::translate("mainWindowClass", "\346\211\200\345\261\236\344\273\243\347\220\206\347\273\223\346\236\204:", Q_NULLPTR));
        label_branch_val->setText(QApplication::translate("mainWindowClass", "\346\267\261\345\234\263\351\207\221\350\201\224\351\200\232\344\277\241\346\201\257\347\247\221\346\212\200\346\234\211\351\231\220\345\205\254\345\217\270", Q_NULLPTR));
        label_server->setText(QApplication::translate("mainWindowClass", "\346\234\215\345\212\241\345\231\250:", Q_NULLPTR));
        label_server_val->setText(QApplication::translate("mainWindowClass", "\345\244\226\347\275\221\351\200\232\350\256\257\346\234\215\345\212\241\345\231\250A", Q_NULLPTR));
        label_server_status->setText(QApplication::translate("mainWindowClass", "\350\241\214\346\203\205\350\277\236\346\216\245\347\212\266\346\200\201:", Q_NULLPTR));
        label_server_status_val->setText(QApplication::translate("mainWindowClass", "\350\277\236\346\216\245", Q_NULLPTR));
        label_quote_space->setText(QApplication::translate("mainWindowClass", "\346\212\245\344\273\267\351\227\264\351\232\2241", Q_NULLPTR));
        label_quote_space_2->setText(QApplication::translate("mainWindowClass", "\346\212\245\344\273\267\351\227\264\351\232\2242", Q_NULLPTR));
        label_sell_vol6->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_sell6->setText(QApplication::translate("mainWindowClass", "\345\215\226\345\205\255", Q_NULLPTR));
        label_sell_price6->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_30->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_sell_vol7->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_sell7->setText(QApplication::translate("mainWindowClass", "\345\215\226\344\270\203", Q_NULLPTR));
        label_sell_price7->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_40->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_sell_vol8->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_sell8->setText(QApplication::translate("mainWindowClass", "\345\215\226\345\205\253", Q_NULLPTR));
        label_sell_price8->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_41->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_sell_vol9->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_sell9->setText(QApplication::translate("mainWindowClass", "\345\215\226\344\271\235", Q_NULLPTR));
        label_sell_price9->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_42->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_sell10->setText(QApplication::translate("mainWindowClass", "\345\215\226\345\215\201", Q_NULLPTR));
        label_sell_vol10->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_sell_price10->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_43->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_buy_price9->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_44->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_45->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_buy_price10->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_buy8->setText(QApplication::translate("mainWindowClass", "\344\271\260\345\205\253", Q_NULLPTR));
        label_buy10->setText(QApplication::translate("mainWindowClass", "\344\271\260\345\215\201", Q_NULLPTR));
        label_buy7->setText(QApplication::translate("mainWindowClass", "\344\271\260\344\270\203", Q_NULLPTR));
        label_46->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_buy_vol10->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_buy6->setText(QApplication::translate("mainWindowClass", "\344\271\260\345\205\255", Q_NULLPTR));
        label_buy_price8->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_buy_vol9->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_buy_vol6->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_buy_vol7->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_buy_price7->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_buy_price6->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
        label_47->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_buy9->setText(QApplication::translate("mainWindowClass", "\344\271\260\344\271\235", Q_NULLPTR));
        label_buy_vol8->setText(QApplication::translate("mainWindowClass", "00", Q_NULLPTR));
        label_48->setText(QApplication::translate("mainWindowClass", "/", Q_NULLPTR));
        label_sell2->setText(QApplication::translate("mainWindowClass", "\345\215\226\344\272\214", Q_NULLPTR));
        label_low_price->setText(QApplication::translate("mainWindowClass", "00.00", Q_NULLPTR));
        label_9->setText(QApplication::translate("mainWindowClass", ">=", Q_NULLPTR));
        label_6->setText(QApplication::translate("mainWindowClass", "\344\271\260\345\215\226", Q_NULLPTR));
        pushButton_sell->setText(QApplication::translate("mainWindowClass", "\345\215\226", Q_NULLPTR));
        pushButton_buy->setText(QApplication::translate("mainWindowClass", "\344\271\260", Q_NULLPTR));
        pushButton_closePosi->setText(QApplication::translate("mainWindowClass", "\345\271\263\346\211\213", Q_NULLPTR));
        pushButton_reverse_order->setText(QApplication::translate("mainWindowClass", "\345\217\215\346\211\213", Q_NULLPTR));
        pushButton_changeorder->setText(QApplication::translate("mainWindowClass", "\346\224\271\345\215\225", Q_NULLPTR));
        pushButton_cancelorder->setText(QApplication::translate("mainWindowClass", "\346\222\244\345\215\225", Q_NULLPTR));
        pushButton_cancelallorder->setText(QApplication::translate("mainWindowClass", "\345\205\250\346\222\244", Q_NULLPTR));
        pushButton_pre_send->setText(QApplication::translate("mainWindowClass", "\347\253\213\345\215\263\345\217\221\351\200\201", Q_NULLPTR));
        pushButton_clear_send->setText(QApplication::translate("mainWindowClass", "\346\270\205\347\251\272\345\267\262\345\217\221\351\200\201", Q_NULLPTR));
        pushButton_pre_delete->setText(QApplication::translate("mainWindowClass", "\345\210\240\351\231\244", Q_NULLPTR));
        pushButton_getgoods->setText(QApplication::translate("mainWindowClass", "\346\217\220\350\264\247", Q_NULLPTR));
        pushButton_FunfInOut->setText(QApplication::translate("mainWindowClass", "\345\207\272\345\205\245\351\207\221", Q_NULLPTR));
        label_account_name->setText(QApplication::translate("mainWindowClass", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">\350\264\246\346\210\267\345\220\215\347\247\260:</span></p></body></html>", Q_NULLPTR));
#ifndef QT_NO_TOOLTIP
        pushButton_add->setToolTip(QString());
#endif // QT_NO_TOOLTIP
        pushButton_add->setText(QApplication::translate("mainWindowClass", "\350\264\246\346\210\267\350\256\276\347\275\256", Q_NULLPTR));
        label_account_risk->setText(QApplication::translate("mainWindowClass", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">\351\243\216\351\231\251\345\272\246:</span></p></body></html>", Q_NULLPTR));
        label_account_risk_val->setText(QApplication::translate("mainWindowClass", "0.00", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class mainWindowClass: public Ui_mainWindowClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
